version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - "./:/work:cached"
      - "rails_cache:/work/tmp/cache"
      - "bundle:/usr/local/bundle:cached"
      - "/work/.git"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db/
  db:
    image: postgres:11-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db:
  bundle:
  rails_cache:
