# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

executors:
  default:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          DATABASE_URL: postgres://postgres:@127.0.0.1/tenmei_doc_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: tenmei_doc_test
          POSTGRES_PASSWORD: ""

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

  yarn:
    executor: default
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - attach_workspace:
          at: .
      - run:
          command: yarn run webpack
      - run:
          command: |
            bundle exec rspec \
              --profile \
              --format RspecJunitFormatter \
              --out tmp/results/rspec.xml \
              --format progress

  rubocop:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop \
              --parallel \
              -f html \
              -o /tmp/artifacts/rubocop-results.html \
              -f progress

  brakeman:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run brakeman
          command: |
            bundle exec brakeman -o /tmp/artifacts/brakeman_output.html

  yaml-lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run yaml-lint
          command: |
            bundle exec yaml-lint -i config/

  haml-lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run haml-lint
          command: |
            bundle exec haml-lint app/views

workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - yarn
      - test:
          requires:
            - setup
            - yarn
      - rubocop:
          requires:
            - setup
      - brakeman:
          requires:
            - setup
      - yaml-lint:
          requires:
            - setup
      - haml-lint:
          requires:
            - setup
