# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

executors:
  default:
    # specify the version you desire here
    - image: circleci/ruby:2.7.1-node-browsers
      environment:
        - RAILS_ENV: test
        - BUNDLE_JOBS: 4
        - DATABASE_URL: postgres://postgres:@127.0.0.1/tenmei_doc_test

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/postgres:11-alpine-ram
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: tenmei_doc_test
        POSTGRES_PASSWORD: ""

  working_directory: ~/repo

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Download and cache dependencies
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      - ruby/save-cache

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  yarn:
    executor: default
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      - ruby/run-tests

  rubocop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      # run rubocop
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop \
              --parallel \
              -f html \
              -o /tmp/artifacts/rubocop-results.html \
              -f progress

  brakeman:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      # run brakeman
      - run:
          name: run brakeman
          command: |
            bundle exec brakeman -o /tmp/artifacts/brakeman_output.html

  yaml-lint:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      # run yaml-lint
      - run:
          name: run yaml-lint
          command: |
            bundle exec yaml-lint -i config/

  haml-lint:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler -v 2.1.4
      - ruby/load-cache
      - ruby/install-deps
      # run yaml-lint
      - run:
          name: run haml-lint
          command: |
            bundle exec haml-lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
            - yarn
      - rubocop:
          requires:
            - build
      - brakeman:
          requires:
            - build
      - yaml-lint:
          requires:
            - build
      - haml-lint:
          requires:
            - build
