default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tenmei_dic_development

test:
  <<: *default
  database: tenmei_dic_test

production:
  <<: *default
  database: tenmei_dic_production
  username: tenmei_dic
  password: <%= ENV['TENMEI_DIC_DATABASE_PASSWORD'] %>
